package it.polimi.ingsw.network.message;

public enum MessageType {
    LOGIN_REQUEST,
    PLAYER_NUMBER_REPLY,
    ASSISTANT_CARD_REPLY,
    MOTHER_NATURE_STEPS_REPLY,
    CLOUD_CHOICE_REPLY,
    MOVE_TO_TABLE_REPLY,
    MOVE_TO_ISLAND_REPLY,
    CHARACTER_CARD_REPLY
}
