package it.polimi.ingsw.network.message;

public enum MessageType {
    LOGIN_REQUEST,
    JOIN_GAME,
    CREATE_GAME,
    PLAYER_NUMBER_REPLY,
    ASSISTANT_CARD_REPLY,
    MOTHER_NATURE_STEPS_REPLY,
    CLOUD_CHOICE_REPLY,
    MOVE_TO_TABLE_REPLY,
    MOVE_TO_ISLAND_REPLY,
    CHARACTER_CARD_REPLY,
    WIZARD_ID,
    SUCCESS_MESSAGE,
    ERROR_MESSAGE,
    GENERIC,
    ASK_TYPE,
    ASSISTANT_CARDS_PLAYED,
    GAME_STATUS,
    SHOW_DECK_MESSAGE,
    ACTION_CHOICE
}
